### ISSUE TITLE
[1.20.1] CRASH: Incompatibility with Better Nether

### ISSUE THREAD

**Issue by DeshiDesu** [Globox1997/MedievalWeapons#118]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

medievalweapons-1.4.6.jar

### Describe the Issue

Picking up any item from Medieval Weapons will crash the server when installed alongside Better Nether.

The message below appears in console:
> [23:08:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Adding item to inventory
	at net.minecraft.class_3242.method_14357(class_3242.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class net.minecraft.class_1829 (net.minecraft.class_1739 and net.minecraft.class_1829 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @62e136d3)
	at net.medievalweapons.item.Long_Sword_Item.initializeState(Long_Sword_Item.java:518) ~[medievalweapons-1.4.6.jar:?]
	at net.minecraft.class_1799.handler$zef000$betternether$bn_init(class_1799.java:1593) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7385(class_1661.java:211) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7366(class_1661.java:202) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7367(class_1661.java:277) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7394(class_1661.java:263) ~[client-intermediary.jar:?]
	at net.minecraft.class_1542.method_5694(class_1542.java:360) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_7341(class_1657.java:627) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:600) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[client-intermediary.jar:?]
	... 6 more

### latest.log

[latest.log](https://github.com/Globox1997/MedievalWeapons/files/12387143/latest.log)

### Do you use any other mods except the required ones?

better-nether-9.0.9.jar
cloth-config-11.1.106-fabric.jar
bclib-3.0.13.jar

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/MedievalWeapons/commit/591c99742c89aecf93b592c3e449057d729877ba](https://github.com/Globox1997/MedievalWeapons/commit/591c99742c89aecf93b592c3e449057d729877ba)

**Comment by DeshiDesu** [comment]
thanks
