### ISSUE TITLE
Game crashes with pehkui 

### ISSUE THREAD

**Issue by SirResigmenduken** [Globox1997/MedievalWeapons#28]
If pehkui is installed, regardless if the player is affected by it, it seems to crash the game when they hit the f5 key while holding an item. Crash error says:

Error: java.lang.IllegalStateException: Pose stack not empty
Exit code: -1

**Comment by SirResigmenduken** [comment]
Figured out it is on pehkui's side, not this mod, as it crashed with another weapons mod. I'm posting this in their github's issue page instead

**Comment by SirResigmenduken** [comment]
I thought I had fixed it, turns out the crash only applies to specific weapons. I found out it seems to only affect the bigger weapons, such as the lance or double-handed axe. Having the item on a backtools slot also seems to cause a crash as well.

**Comment by AzureMonument** [comment]
I just discovered something similar on a server when I attempt to hold a healing staff: 

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1472) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1235) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1026) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.redirect$zlc000$redirectRenderingWorld(class_757.java:4122) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:810) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/11/21, 1:59 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zlc000$redirectRenderingWorld(class_757.java:4122)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$zlc000$redirectRenderingWorld(class_757.java:4122)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$dfg000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['Aojae'/5081, l='ClientWorld minecraft:overworld', x=31.11, y=58.00, z=27.30]]
	Chunk stats: Client Chunks (ImmPtl) 512
	Level dimension: minecraft:overworld
	Level spawn location: World: (-126,63,-57), Section: (at 2,15,7 in -8,3,-4; chunk contains blocks -128,-64,-64 to -113,319,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 43377 game time, 43377 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 666101472 bytes (635 MiB) / 2684354560 bytes (2560 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9415
	Graphics card #1 name: NVIDIA GeForce RTX 2070 Super
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1e91
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 77656.42
	Virtual memory used (MB): 47582.59
	Swap memory total (MB): 45056.00
	Swap memory used (MB): 942.43
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx10240m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.0.0
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancedcompass: Advanced Compass 1.2.1
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.3.24
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.3-1.17
		bclib: BCLib 0.3.0
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		bettermounthud: Better Mount HUD 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		blast: BLAST 1.6.2
		blockus: Blockus 2.2.8+1.17.1
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0-nightly.1.17-pre2
		carrier: Carrier 1.8.0
		cauldronconcrete: Cauldron Concrete 1.0.0+21w16a-fabric
		charm: Charm 3.3.2
		chat-up: Chat Up! 2.0
		cherishedworlds: Cherished Worlds 1.4.1-1.17
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.37
		clumps: Clumps fabric-1.17.1-7.0.4
		collectionorigins1: Imperium Origins Collection 1 2.0
		colormeoutlines: Color Me Outlines 1.0.1
		colouredmoss: Colorful Azaleas 1.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.5-1.17.1
		controlling: Controlling For Fabric 1.1.2
		cpas: cpas 2.0.0
		cpas-api: cpas-api 2.0.0
		cpas-runtime: cpas-runtime 2.0.0
		crawl: Crawl 0.9.1
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customstars: Custom Stars 0.5
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dual_riders: DualRiders 1.0.5
		ducts: Ducts 1.1.4
		dynamicfps: Dynamic FPS 2.0.4
		easyautocrafting: EasyAutoCrafting 1.1+1.17
		elytraboosters: Elytra Boosters Mod 1.2.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		environmentz: EnvironmentZ 1.1.4
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.1
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabrication: Fabrication 2.0.0-pre3
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.2
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.0.2
		flonters: Flonters 1.2.1+1.17.1
		freelook: freelook 1.1.0
		frex: FREX 5.2.223
		geckolib3: Geckolib 3.0.8
		glowingbanners: Glow Banners 1.0.2
		hidearmor: Hide Armor 2.4
		hydrogen: Hydrogen 0.3
		imm_ptl_core: Immersive Portals Core 0.20
		immersive_portals: Immersive Portals 0.20
		impaled: Impaled 1.0.1
		incantationem: Incantationem 1.1
		indypets: Independent Pets 0.5.1
		inventorio: Inventorio 1.6.2
		inventory_control_tweaks: Inventory Control Tweaks 1.3.8+MC1.17-1.17.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		json-model-extensions: JSON Model Extensions 1.22.200
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		krypton: Krypton 0.1.4
		libblockattributes: LibBlockAttributes 0.9.0-pre.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0-pre.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0-pre.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.4+1.17.1
		libmultipart: LibMultiPart 0.6.3
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.6.3
		libnetworkstack: Lib Network Stack 0.5.0
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		lovely_snails: Lovely Snails 1.0.2+1.17
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		magick: Magick: Potions and Pearls 1.0.5
		malilib: MaLiLib 0.10.0-dev.24
		mavm: More Axolotl Variants Mod 1.0.2b
		maybe-data: Maybe data 1.0.1-1.17
		medievalweapons: Medieval Weapons 1.1.6
		minecraft: Minecraft 1.17.1
		miniextras: Mini Extras Mod 1.3.0
		mm: Manningham Mills 2.3
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmenu: Mod Menu 2.0.2
		mooblooms: Mooblooms 1.5.0
		moreorigins: more origins 1.0
		nostrip: No Strip 1.2.1-1.17+
		notenoughanimations: NotEnoughAnimations 1.3.0
		notes: Notes 1.0.6
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		overpoweredmending: OverpoweredMending 2.2.4
		painters_blocks: Painter's Blocks 1.2.3+1.17.1
		paintingcycle: Painting Cycle 1.0.0
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.1
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pettable: Pettable 1.2.0
		playerabilitylib: Pal 1.3.0
		pride: Pride Lib 1.0.0+21w03a
		projectsavethepets: Project: Save the Pets! 1.0.2+minecraft-1.16.4
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		quicksand: Quicksand 1.0.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		respawnablepets: Respawnable Pets 1.17-3
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		rpgstats: RPGStats 4.1.8+1.17.1
		rpgz: RPGZ 0.4.8
		scaffoldforever: Scaffold Forever 1.1+1.17.1
		schmucks: Schmucks 1.4.0
		scorch: Scorch 1.0.2
		secretrooms: Secret Rooms 1.0.0+1.17
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		sentimentality3: Sentimentality 3 1.3.0
		sheepconsistency: Sheep Consistency 1.0.3
		sihywtcamc: sihywtcamc 1.3.1+1.17.1
		sihywtcamd: sihywtcamd 1.5+1.17.1
		simple_backpack: SimpleBackpack 1.1.17
		simplemeasuring: Simple Measuring 1.0.0
		skylorlib: SkyLib 1.0.0
		somnus: Somnus API 0.0.12-1.17
		soundphysics: Sound Physics 2.0.0
		starlight: Starlight fabric-1.0.0-RC2-3a77ed1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		statuseffecttimer: Status Effect Timer 1.0.2
		taxfreelevels: Tax Free Levels 1.2.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terralith: Terralith for Fabric 1.3
		totemicoverhaul: Totemic Overhaul 1.1.7
		transliterationlib: TRansliterationLib 1.1.0
		transportables: Transportables 1.0.5
		tweakeroo: Tweakeroo 0.10.0-dev.20210710.155746
		twigs: Twigs 1.0.1
		universal_ores: Universal Ores 1.0
		vanilla_essence: Vanilla essence 2.1.2
		vanillatweaks: VanillaTweaks 1.17.1-1.0.10
		vehiclefix: VehicleFix 1.1
		villagernames: Villager Names 2.0.0
		waterdripsound: Drip Sounds 1.17-0.2.1
		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
		windowedfullscreen: Windowed Fullscreen 1.0.0
		witherturnsskeletons: Wither turns Skeletons 1.0.0
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		yungsapi: YUNG's API 1.17-Fabric-15
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.9415, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jayco\Desktop\Minecraft\MultiMC\instances\Fab 1.17.1 v1\.minecraft\crash-reports\crash-2021-08-11_13.59.38-client.txt

**Comment by SirResigmenduken** [comment]
Your mod list also has pehkui, so I think it's the same confliction.
