### ISSUE TITLE
problem with loading minecraft | compatibility issue with additional additions | fabric 1.19

### ISSUE THREAD

**Issue by Surpos0** [Globox1997/MedievalWeapons#79]
I updated medieval weapons to 1.3.0 and started minecraft, but minecraft just in the end of loading stared repeat loading over and over again, and never shows menu screen. And this is only happening with newest version of mod.

this is log from loading game:
[log.txt](https://github.com/Globox1997/MedievalWeapons/files/9426692/log.txt)

i looked in log and i think this is reason why, but idk
Caused by: java.lang.IllegalArgumentException: Failed to create model for minecraft:pig
	at net.minecraft.class_5619.method_32174(class_5619.java:158) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:381) ~[client-intermediary.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 125 more
Caused by: java.lang.NullPointerException: null key in entry: null=net.medievalweapons.entity.renderer.Javelin_Entity_Renderer@5292dbe8
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:337) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:447) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.class_5619.method_32174(class_5619.java:156) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:381) ~[client-intermediary.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 125 more

**Comment by Romz24** [comment]
I confirm, I have the same problem on version **1.3.0**. I checked **1.2.1**, there is no such problem there.

**Comment by Surpos0** [comment]
when you install both of this mods game just can't load menu.

https://user-images.githubusercontent.com/110408444/186924729-f353955a-548a-4c4d-a817-67958848f237.mp4

mods versions:
additional additions - 5.0.1 - https://www.curseforge.com/minecraft/mc-mods/additional-additions
medieval weapons - 1.3.0

**Comment by Globox1997** [comment]
Thanks for reporting it, fixed with [https://github.com/Globox1997/MedievalWeapons/commit/bfef026a8def240b584f57597a71dc2b874e327e](https://github.com/Globox1997/MedievalWeapons/commit/bfef026a8def240b584f57597a71dc2b874e327e)
