### ISSUE TITLE
Javelin in enchanting table caused server crash

### ISSUE THREAD

**Issue by Flyvee** [Globox1997/MedievalWeapons#85]
When a javelin is placed in the enchantment table, no enchantments for it is generated and while it only gives an error in singleplayer in the logs, on the server, it caused the server to crash. This is with any of the javelin including those from better end.
Here is the specific error:
Failed to handle packet net.minecraft.class_2813@489c4d95, suppressing error
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:303)
	at net.minecraft.class_3244.method_12076(class_3244.java:1770)
	at net.minecraft.class_2813.method_12191(class_2813.java:58)
	at net.minecraft.class_2813.method_11054(class_2813.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "currentEnchantments" is null
	at net.minecraft.class_1890.handler$ccc000$getPossibleEntriesMixin(class_1890.java:1047)
	at net.minecraft.class_1890.method_8229(class_1890.java)
	at net.minecraft.class_1890.method_8230(class_1890.java:365)
	at net.minecraft.class_1718.method_7637(class_1718.java:212)
	at net.minecraft.class_1718.method_17411(class_1718.java:127)
	at net.minecraft.class_3914.method_17394(class_3914.java:35)
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
	at net.minecraft.class_3914.method_17393(class_3914.java:34)
	at net.minecraft.class_1718.method_7609(class_1718.java:106)
	at net.minecraft.class_1718$1.method_5431(class_1718.java:32)
	at net.minecraft.class_1277.redirect$bnm000$fabric_redirectMarkDirty(class_1277.java:543)
	at net.minecraft.class_1277.method_5447(class_1277.java:140)
	at net.minecraft.class_1735.method_7673(class_1735.java:61)
	at net.minecraft.class_1735.method_32755(class_1735.java:151)
	at net.minecraft.class_1703.method_30010(class_1703.java:414)
	at net.minecraft.class_1703.method_7593(class_1703.java:293)
	... 17 more

	
	And the server crash log:
	[crash-2022-10-23_16.50.02-server.txt](https://github.com/Globox1997/MedievalWeapons/files/9847107/crash-2022-10-23_16.50.02-server.txt)

**Comment by Globox1997** [comment]
Might be fixed with [https://github.com/Globox1997/MedievalWeapons/commit/1c9f4891e27da2c8660396afe28e714b10452351](https://github.com/Globox1997/MedievalWeapons/commit/1c9f4891e27da2c8660396afe28e714b10452351)

**Comment by Globox1997** [comment]
Reopen if still persistent.
